version: '3.8'
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    container_name: admin-loker-service-go
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - digylabs-admin-loker-service
    depends_on:
      - db
  ### ===================
  ### DB SERVICE
  ### ===================
  # database:
  #   image: postgres:latest
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - 5435:5432
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   networks:
  #     - digylabs-admin-loker-service
  ### ========================
  ### VOLUMES PERSISTENT DATA
  ### ========================
# volumes:
#   pg-data:
  ### ===================================
  ### NETWORKS GROUP FOR ONE SAME SERVICE
  ### ===================================
networks:
  digylabs-admin-loker-service:
