version: '3.8'
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - pos_network
    depends_on:
      - db
  ### ===================
  ### DB SERVICE
  ### ===================
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5435:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pos_network
  ### ========================
  ### VOLUMES PERSISTENT DATA
  ### ========================
volumes:
  pg-data:
  ### ===================================
  ### NETWORKS GROUP FOR ONE SAME SERVICE
  ### ===================================
networks:
  pos_network:
